version: '3.7'
services:
  mysql:
    image: mysql:8.0.18
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=mynewpassword
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password